#### 目录

* `C`语言错误处理
* `C++`异常处理
* `C++`异常处理优点

##### `C`语言错误处理方法

* 返回值（`if...else`语句判断错误）

  * ```c
    int copy(const char* src,const char* dst)
    {
        open(src)
            return -1;
        open(dst)
            return -2;
        read(src,buf)
            return -3;
        write(dst,buf)
            return -4;
        return 0;
    }
    
    void fun()
    {
        int ret;
        ret = copy(src,dst);
        if(ret == -1)
        {}
        else if(ret == -2)
        {}
        else if(ret == -3)
        {}
        else if(ret == -4)
        {}
        ret = copy(src,dst); // 每次调用copy都需要对返回值进行判断，来进行错误处理
    }
    ```

  * 容易遗漏

* `errno`

  * 系统调用与`C`库调用，返回值是`-1`，并且将错误代码放在`errno`全局变量中

* `goto`语句：局部`(函数内部)`跳转

  * ```c++
    int test()
    {
        char* p1 = (char*)malloc(10);
        if(p1!=NULL)
        {
            ...
        }
        else 
            goto POS1;
        ...
        char* p2 = (char*)malloc(10);
        if(p2!=NULL)
        {
            ...
        }
        else
            goto POS2;
        ...
        ...
    POS1:
        exit(1);
    POS2:
        free(p1);
        exit(1);
    }
    ```

* `setjmp、longjmp`

  * 与`C++`中类似，设置**长跳转**（跳出函数范围，使用数组保存栈空间）

    * 不管在哪里出现错误，可以直接跳转到捕获错误代码处

  * ```c++
    #include <stdio.h>
    #include <setjmp.h>
    
    jmp_buf _buf_;  // 保存当前栈环境的数组
    
    double Divide(double a,double b)
    {
        if(b==0.0)
        {
            longjmp(_buf_,1);  // 第二个参数是返回值，出现异常时，返回该值 异常抛出点
        } 
        else return a/b;
    }
    
    int main()
    {
        int ret;
        ret = setjmp(_buf_); // 保存当前栈环境到buf中，设置保存点，跳转到该处
    
        if(ret == 0)  // try
        {
            printf("a/b = %f\n",Divide(5.0,0.0));
        }
        else if(ret == 1)  // catch
        {
            printf("divided by zero\n");
        }
    
        return 0;
    }
    ```

  * **错误抛出点**和**跳转点**比较**远**

  * ```c++
    // cpp方式
    #include <unistd.h>
    #include <iostream>
    using namespace std;
    
    // jmp_buf _buf_;  // 保存当前栈环境的数组
    
    double Divide(double a,double b)
    {
        if(b==0.0)
        {
            throw(1);    // 抛出整型异常
        } 
        else return a/b;
    }
    
    int main()
    {
        try {  // 放置可能产生错误的代码
            cout<<"division..."<<endl;
            cout<<Divide(5.0,0.0)<<endl;
            // 也可在这里抛出异常，可以在远处抛出异常，
        }
        catch(int)   // 捕获整型异常
        {
            printf("divided by zero\n");
        }
        return 0;
    }
    ```

* `C`语言的出错处理常被认为是紧耦合的，函数使用者必须在非常靠近函数调用的地方编写错误处理代码

  * 使得其变得笨拙以及难以使用

##### `C++`异常处理

* `try+catch+throw`

##### `C++`异常处理优点

* 不会与“正常”代码混在一起
* 在某个区域集中进行错误处理
* 多次调用同一个函数，只需在一个地方编写一次错误处理代码
* **错误不能被忽略**